### ISSUE TITLE
up and down arrow not displaying on android

### ISSUE THREAD

**Issue by lukecr** [tefra/navgoco#21]
hi

i just thought i'd let you know the up and down arrows don't show up on android

other than that, nice little menu - many thanks :)

luke

**Comment by dasginganinja** [comment]
I have a solution for this issue!  The problem is that Android doesn't have these unicode characters so you'll need to use a suitable replacement.  I chose to use the following:
U+25B2 (Black up-pointing triangle ▲)
U+25BC (Black down-pointing triangle ▼)

https://github.com/tefra/navgoco/blob/master/src/jquery.navgoco.css#L43-L48
You need to make changes to these lines to get this to work.

Cheers!

**Comment by cemkaan** [comment]
How to add U+25B2 instead of \25be ?
I tried     
font-family: Arial Unicode MS, Lucida Sans Unicode, sans-serif;
	content: '\e296bc';
It added question marked error.

**Comment by dasginganinja** [comment]
cemkaan,

Have you tried change it to:
```css
.nav li > a > span:after {
    content: '\25b2';
}
.nav li.open > a > span:after {
    content: '\25bc';
}
```
That's how I did it before.
